version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx01
    ports: 
      - "8000:8000"
    volumes: 
      - /Users/rkirby/repo/tesserack-rest:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on: 
      - web
  web:
    build: .
    container_name: django01
    depends_on: 
      - db
    volumes: 
      - /Users/rkirby/repo/tesserack-rest:/src
    expose:
      - "8000"
  jenkins:
    image: 844895670466.dkr.ecr.us-east-1.amazonaws.com/jenkins-images:provisioned-master-latest
    container_name: jenkins-master
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    container_name: postgres01
