---
- name: Download all LoyaltyOnDemand Rest Installers from S3 Bucket to Instance
  win_shell: |
    $installerRepository = '{{cicd_pipeline_s3_bucket}}'

    $region = '{{build_region}}'
    $keyPrefix = 'build/deployment-artifacts/loyalty-navigator/'

    $localPath = 'C:/build/deployment-artifacts/loyalty-navigator'

    if (-Not (Test-Path -Path $localPath)){New-Item -Path $localPath -ItemType directory -Force | out-null}
    $artifacts = Get-S3Object -BucketName $installerRepository -KeyPrefix $keyPrefix -Region $region
    foreach($artifact in $artifacts) {$localFileName = $artifact.Key -replace $keyPrefix, ''
    if ($localFileName -ne '') {$localFilePath = Join-Path $localPath $localFileName
    Copy-S3Object -BucketName $installerRepository -Key $artifact.Key -LocalFile $localFilePath -Region $region}}
  retries: 3
  delay: 10

#- name: Install .Net Core 2.0.0
#  win_shell: Start-Process -FilePath ./dotnet-runtime-2.0.0-win-x64 -ArgumentList "/q /norestart" -Wait -Verb RunAs
#  args:
#    chdir: c:\build\deployment-artifacts\rest-api

- name: Pause for all installations to complete
  pause: minutes=2

- name: Delete all Scripts, Installers, and Scheduled Tasks
  win_shell: |
    Remove-Item -Recurse -Force  c:\build\deployment-artifacts\loyalty-navigator
