template_path: templates/instances.py
parameters:
    LoadBalancerName: JenkinsDevELB
    AMIID: ami-56a5f329
    SLAVEAMIID: ami-a5a6f0da
    PublicSubnet1: !stack_output vpc::PublicSubnetA
    PrivateSubnet1: !stack_output vpc::PrivateSubnetA
    KeyPair: jenkins-development
    LoadBalancerSecurityGroup: !stack_output securitygroups::LoadBalancerSecurityGroup
    InstanceSecurityGroup: !stack_output securitygroups::InstanceSecurityGroup
    SlaveInstanceSecurityGroup: !stack_output securitygroups::SlaveInstanceSecurityGroup
    AvailabilityZoneA: !stack_output vpc::AvailabilityZone1
    AvailabilityZoneB: !stack_output vpc::AvailabilityZone2
