template_path: templates/vpc.py
parameters:
    VpcCidr: 10.0.0.0/16
    PublicSubnetA: 10.0.10.0/24
    PrivateSubnetA: 10.0.20.0/24
    AvailabilityZoneA: us-east-1a
    AvailabilityZoneB: us-east-1b
