template_path: templates/rest_api.py
parameters:
    VpcId: !stack_output vpc::VpcId
    AdminCidrBlock: !stack_output vpc::AdminCidrBlock
    RESTPrivSubnet1: !stack_output vpc::RESTPrivSubnet1
    RESTPrivSubnet2: !stack_output vpc::RESTPrivSubnet2
    RESTPubSubnet1: !stack_output vpc::RESTPubSubnet1
    RESTPubSubnet2: !stack_output vpc::RESTPubSubnet2
    KongPrivateLoadBalancerSecurityGroup: !stack_output kong::KongPrivateLoadBalancerSecurityGroup
    OAuthInternalLoadBalancerSSMParameterValue: !stack_output kong::KongPrivateInternalLoadBalancerDNS
    RestApiImageId: ami-02446b7963e3dee94
    RestApiKeyName: pd-cicd-devolopment
    RestApiInstanceType: t2.medium
    RestApiIAMInstanceProfile: cicd-admin-role
    RestApiASGGroupMinSize: "1"
    RestApiASGGroupDesiredSize: "1"
    RestApiASGGroupMaxSize: "1"
    RestApiASGHealthCheckType: ELB
    RestApiASGHealthCheckGracePeriod: "300"
    RestApiASGCoolDown: "120"
    RestApiASGLifeCycleTransition: autoscaling:EC2_INSTANCE_LAUNCHING
    RestApiASGLifeCycleHeartBeatTimeout: "900"
    RestApiPrefixSSMParameterValue: lod
    OAuthRestApiProvisionKeySSMParameterValue: "12"
    OAuthRestApiKongConsumerClientIdSSMParameterValue: "33"
    OAuthRestApiKongConsumerClientSecretSSMParameterValue: "34"
    LoyaltyOnDemandOrganizationSSMParameterValue: D1PDEV
    LoyaltyOnDemandEnvironmentSSMParameterValue: Development
hooks:
    #before_create:
    #    - !execute_http_requests uat/restapi::configure # The argument is accessible via self.argument
    after_create:
        - !refresh_lod_rest_api_servers "dev::restapi"
    after_update:
        - !refresh_lod_rest_api_servers "dev::restapi"
