apiVersion: v1
kind: Service
metadata: 
  name: jenkins-service 
  labels: 
    app: jenkins
spec: 
  ports: 
  - port: 3000
    targetPort: jenkins-port 
  selector: 
    app: jenkins 
  type: LoadBalancer
