apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master-deployment
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-master
        image: 844895670466.dkr.ecr.us-east-1.amazonaws.com/jenkins-images:provisioned-master-latest
        imagePullPolicy: Always
        ports:
        - name: jenkins-port
          containerPort: 8080
