apiVersion: apps/v1
kind: Deployment
metadata:
  name: launchpad-django
spec:
  selector:
    matchLabels:
      app: launchpad
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: launchpad
    spec:
      containers:
      - name: launchpad-django
        image: 844895670466.dkr.ecr.us-east-1.amazonaws.com/launchpad-django:provisioned-latest
        ports:
        - name: launchpad-port
          containerPort: 8000
        imagePullPolicy: Always
