---
- name: Manage Windows Features
  include_tasks: manage-windows-feature.yml
  with_items: "{{ WINDOWS_FEATURES }}"

- name: Install Base Windows Prerequisites 
  include_tasks: base-windows-installs.yml
