# Install AWS Iam Authenticator

install:
	curl -o aws-iam-authenticator  https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
	chmod +x aws-iam-authenticator
	chown jenkins.jenkins aws-iam-authenticator
	mv aws-iam-authenticator /usr/local/bin/
