pipeline {
    agent any

    stages {
        stage('Setup') {
            steps {
                echo 'Setup Environment'
                sh 'echo ${BUILD_REGION}'
                sh 'echo ${BUILD_ENVIRONMENT}'
            }
        }
        stage('Generate Vars File'){
        steps {
               sh 'python3 jenkins-pipeline/packer/build_image.py --procedure ${PROCEDURE}'
           }
        }
        stage('Build Image') {
            steps {
               echo 'Build Packer Image'

               sh '''cd packer/builds/"${IMAGE_TYPE}" && packer.io build -var-file=../../../vars_file.json ${IMAGE_TYPE}.packer'''
            }
            post {
            failure {
            mail to: 'dpreble@brierley.com',
                 subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                 body: "Something is wrong with ${env.BUILD_URL}"

             }
          }
        }
        stage('Create Environment') {
        steps {
           echo 'Creating Environment From Image'
          }
        }
      }
      post {
            success {
            mail to: 'dpreble@brierley.com',
                 subject: "Successful Pipeline: ${currentBuild.fullDisplayName}",
                 body: "Build Completed Successfully: ${env.BUILD_URL}"
      }

    }
}

