 - name: Update Repository List
   shell: apt-get update -y
   become: true

 - name: Install Python3
   shell: apt-get install -y python3
   become: true

 - name: Install Python3 Pip
   shell: apt-get install -y python3-pip
   become: true

 - name: Install Python3 Development Tools
   shell: apt-get install -y libssl-dev libffi-dev python-dev
   become: true

 - name: Install Boto3
   shell: pip3 install boto3
   become: true

 - name: Install AWS CLI
   shell: pip3 install awscli
   become: true

 - name: Install Ansible
   shell: pip3 install ansible
   become: true

 - name: Download Packer
   get_url:
     url: https://releases.hashicorp.com/packer/1.2.4/packer_1.2.4_linux_amd64.zip
     dest: /opt/packer.zip
     checksum: sha256:258d1baa23498932baede9b40f2eca4ac363b86b32487b36f48f5102630e9fbb
     owner: jenkins
     group: jenkins
   become: true

 - name: Unzip Packer
   unarchive:
     src: /opt/packer.zip
     dest: /opt/
     remote_src: yes
   become: true

 - name: Change Permissions of Packer
   file:
     path: /opt/packer
     owner: jenkins
     group: jenkins
   become: true

 - name: Create Symbolic Link
   file:
     src: /opt/packer
     dest: /usr/local/bin/packer.io
     owner: jenkins
     group: jenkins
     state: link
   become: true

 - name: Install JQ Json Parser
   shell: apt-get install -y jq
   become: true

 - name: Install sceptre
   shell: pip3 install sceptre
   become: true

 - name: Install Troposphere
   shell: pip3 install troposphere
   become: true

 - name: Install requests
   shell: pip3 install requests
   become: true

 - name: Install Awacs
   shell: pip3 install awacs
   become: true

 - name: Add NodeJS PPA
   shell: curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
   become: true

 - name: Install NodeJS and NPM
   shell: apt-get install nodejs
   become: true

 - name: Install Newman
   shell: npm install -g newman
   become: true

 - name: Add kubectl Google GPG Ring
   shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
   become: true

 - name: Update Sources List
   shell: echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
   become: true

 - name: Update Repository
   shell: apt-get update -y
   become: true

 - name: Install Kubectl
   shell: apt-get install -y kubectl
   become: true

 - name: Download AWS Iam Authenticator
   shell: curl -o /opt/aws-iam-authenticator  https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
   become: true

 - name: Add Execute Permissions Bit
   shell: chmod +x /opt/aws-iam-authenticator
   become: true

 - name: Change Ownership of Authenticator
   shell: chown jenkins.jenkins /opt/aws-iam-authenticator
   become: true

 - name: Move Authenticator to Path
   shell: mv /opt/aws-iam-authenticator /usr/local/bin/
   become: true
