 - name: Add NodeJS PPA
   shell: curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
   become: true

 - name: Add kubectl Google GPG Ring
   shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
   become: true

 - name: Add Kubernetes Packages To Sources List
   shell: echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
   become: true

 - name: Update Repository List
   shell: apt-get update -y
   become: true

 - name: Install Package List
   apt:
     name: "{{ packages }}"
   vars:
     packages:
     - python3
     - python3-pip
     - libssl-dev
     - libffi-dev
     - python-dev
     - jq
     - nodejs
     - kubectl
   become: true

 - name: Copy requirements.txt to Server
   copy:
     src: files/requirements.txt
     dest: /opt/requirements.txt
   become: true

 - name: Install Requirements
   shell: pip3 install -r /opt/requirements.txt
   become: true

 - name: Copy Automation Files to Server
   copy:
     src: files/make
     dest: /opt/
   become: true

 - name: Install Packer
   make:
     chdir: /opt/make/packer
     target: install
   become: true

 - name: Install Jenkins Job Builder
   make:
     chdir: /opt/make/jobbuilder
     target: install
   become: true

 - name: Install AWS Iam Authenticator
   make:
       chdir: /opt/make/iam
       target: install
   become: true

 - name: Install Newman
   shell: npm install -g newman
   become: true
