template_path: templates/instances.py
parameters:
    LoadBalancerName: JenkinsDevELB
    AMIID: ami-06457179
    SLAVEAMIID: ami-ea477395
    PublicSubnet1: !stack_output vpc::PublicSubnetA
    PrivateSubnet1: !stack_output vpc::PrivateSubnetA
    KeyPair: prod-nvirginia-launchpad-jenkins
    LoadBalancerSecurityGroup: !stack_output securitygroups::LoadBalancerSecurityGroup
    InstanceSecurityGroup: !stack_output securitygroups::InstanceSecurityGroup
    SlaveInstanceSecurityGroup: !stack_output securitygroups::SlaveInstanceSecurityGroup
    AvailabilityZoneA: !stack_output vpc::AvailabilityZone1
    AvailabilityZoneB: !stack_output vpc::AvailabilityZone2
